### ISSUE TITLE
Mastery level trigger - skill reset

### ISSUE THREAD

**Issue by kellewic** [Alorel/melvor-action-workflows#103]
### Platform

Steam

### Category

A bugged trigger

### Bug description

When creating a master level trigger, the skill value is cleared upon choosing a recipe.

### Steps to reproduce

1. Choose Mastery Level trigger
2. Choose a skill - doesn't matter which one
3. Choose a recipe
4. The skill value will clear

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] I have searched for similar issues and nothing similar exists

**Comment by Alorel** [comment]
Very likely related: #95

I should have time to start fixing stuff again tomorrow, been a busy week...
