### ISSUE TITLE
Feature: GP Trigger

### ISSUE THREAD

**Issue by Makeshift** [Alorel/melvor-action-workflows#107]
### Category

A new trigger

### What are you missing?

Hi!

Fantastic mod, absolutely loving playing with it.

I'm not sure if I'm dumb and missed it, but I don't think there's a trigger for GP amount? I couldn't find it in the item trigger list, at least.

I was trying to make a workflow that bought summoning shards when they were low, and then sold specific items when my GP was low, but couldn't find a way to trigger when my GP was low.

Cheers!

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] My request fits the contribution guidelines
- [X] I have searched for similar issues and nothing similar exists

**Comment by Alorel** [comment]
That's a super simple one, I'll get it patched in the next few days when I get a chance to code again :slightly_smiling_face:
