### ISSUE TITLE
Equipped Item Count support

### ISSUE THREAD

**Issue by Timmarus** [Alorel/melvor-action-workflows#123]
### Category

Additions to the mod API

### What are you missing?

It seems that equipped item counts aren't taken into account when using the Item Quantity trigger. I would like to suggest adding this in as it would greatly expand the amount of workflows possible.

For example, I'm trying to setup a loop to make Devils and use them in firemaking until I run out, but when the "Equip Devil" step executes, my "Item Quantity" becomes 0 and it automatically triggers my "Make Devil" step again.

It could either be added as part of the Item Quantity trigger or maybe added as it's own trigger, like "Equipped Item Quantity" or something.

Thanks for reading!

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] My request fits the contribution guidelines
- [X] I have searched for similar issues and nothing similar exists

**Comment by Alorel** [comment]
Yup, item quantity is different as it only counts stuff in your bank.

I'll get this done for (probably) the next version, but I'm taking a little break just now so it'll likely be after all the holidays 🙂

**Comment by Timmarus** [comment]
Cool, just wanted to make sure you knew about it! Take your time and happy holidays!
