### ISSUE TITLE
Feature Request: Pet Unlocked

### ISSUE THREAD

**Issue by Shirotsumekusa** [Alorel/melvor-action-workflows#124]
### Category

A new trigger

### What are you missing?

I was wondering if it would be possible to add a pet unlocked trigger? That's something the old Action Queue had that was very useful.
Thank for your hard work!

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] My request fits the contribution guidelines
- [X] I have searched for similar issues and nothing similar exists

**Comment by Alorel** [comment]
Done, it'll get published sometime this year :slightly_smiling_face:
