### ISSUE TITLE
And / Or functionality

### ISSUE THREAD

**Issue by kellewic** [Alorel/melvor-action-workflows#125]
### Category

Question about a Trigger

### Question

I'm not sure what's going on, but the following didn't work:

![cooking-and-or](https://user-images.githubusercontent.com/3178267/209416663-d0ac7595-cc65-4b7f-8540-4352d1447564.jpg)

but this one did:

![cooking-or-and](https://user-images.githubusercontent.com/3178267/209416667-238a9e1a-ca0d-4602-b710-948a245e4607.jpg)

Posting this as a question since I'm not sure if I'm doing something wrong or it's a bug since they should be functionally equivalent as:

`(Item Quantity Magma Fish >= 10000 && Mastery Level Cooking: Magma Fish == 99) || (Item Quantity Raw Magma Fish <= 0)`

It wouldn't matter if the first way was interpreted as:

`(Item Quantity Magma Fish >= 10000) && (Mastery Level Cooking: Magma Fish == 99 || Item Quantity Raw Magma Fish <= 0)`

since it should have still changed to the next task as I had more than 10k Magma Fish and hit 99 mastery level in it as well.

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] I have searched for similar issues and nothing similar exists

**Comment by Alorel** [comment]
Hey, unless I'm really misreading the screenshots, the conditions **aren't** the same.

1st one is 

```
(magmaFish >= 10k && mastery >= 99 && (rawMagma <= 0))
```

(the `or` condition only has a single rawMagmafish item and is attached to the top-level `and`)

The 2nd is

```
((magmaFish >= 10k && mastery >= 99) || rawMagma <= 0)
```

**Comment by kellewic** [comment]
I definitely don't understand how it can be a triple AND when the first trigger is an AND with 2 conditions and the next is an OR with one condition. If it's a triple AND, what happened to the OR trigger?

Using the UI, this is how I created the first one...

Choose AND trigger then added the 2 I wanted, then the only thing you can do is click the (+) again to choose another trigger. I did that and chose OR (see next screenshot for result).

![and-or-1](https://user-images.githubusercontent.com/3178267/209891161-86e894b8-25e8-4c3d-98d2-5a601b28e76b.jpg)

Now I have an OR that does appear visually to be inside the AND. Also a new set of icons highlighted in red appear after choosing OR so I tried using the (+) there to create a new OR outside the AND and then delete the OR inside the AND and chaos ensued (see last screenshot).

![and-or-2](https://user-images.githubusercontent.com/3178267/209891336-4125191b-3554-468f-8363-56095a8f273c.jpg)

The second I delete the OR inside the AND, it cleared out the OR I created using the red-highlighted (+) icon outside the AND. Still let me save it though.

![and-or-3](https://user-images.githubusercontent.com/3178267/209891783-72c104f9-532b-4081-b262-2bd1b8c173fb.jpg)

So how do you create the following inside the UI?
```((magmaFish >= 10k && mastery >= 99) || rawMagma <= 0)```

instead of:
```(rawMagma <= 0 || (magmaFish >= 10k && mastery >= 99))```

I know they're the same in the end, but starting with an AND in the UI, how do you get back outside the AND to add the OR? Thanks!

**Comment by Alorel** [comment]
Tbh I think the biggest confusion here comes from the UI itself, I tried to reuse as much of the game's original CSS as possible, but it doesn't look like that's working out too well with just the upper borders.

Think about and/or triggers like you would about `if` statements with multiple brackets in programming.

- What you want here is `condition1 || condition2`, but your `condition2` itself expands into `condition3 && condition4`, so the entire thing ends up looking like `condition1 || (condition3 && condition4)`
- You have an `OR` on the top level - this is your `if` statement as a whole - and an `AND` nested inside - these are the contents within the brackets after the `||`, therefore you need to create an `OR` trigger at the top level and make one of its conditions an `AND` trigger.
- Your [2nd screenshot](https://user-images.githubusercontent.com/3178267/209416667-238a9e1a-ca0d-4602-b710-948a245e4607.jpg) was spot on: the top-level trigger is an `OR`, `magma fish <= 10k` is `condition1`, the `AND` trigger is `condition2`, `magma >= 10k` & `cooking mastery` are `condition3` and `condition4` respectively.

I'll try to update the UI a bit to make it a bit clearer how conditions get grouped.

**Comment by kellewic** [comment]
So in the first way I did it, does it end up reading something like `AND(C1, C2, OR(C3))` essentially making a 3 operand AND?

**Comment by Alorel** [comment]
Yup
