### ISSUE TITLE
Wait action purpose?

### ISSUE THREAD

**Issue by kellewic** [Alorel/melvor-action-workflows#173]
### Category

Question about an Action

### Question

Posting as a question as I might just not understand how the Wait action works.

I had a workflow I wanted to essentially stop whatever I was doing once I hit so many items. Since there's no way I know of to stop actions, I was trying to use a really long wait time, but the Wait action doesn't seem to work.

I created a basic workflow to test it:
```json
["Current", [[[11, {
                    "comparator": "<=",
                    "item": "melvorTotH:Meteorite_Bar",
                    "qty": 21210
                }
            ], [[30, {
                        "recipe": "melvorTotH:Meteorite_Bar"
                    }
                ]]], [[11, {
                    "comparator": ">=",
                    "item": "melvorTotH:Meteorite_Bar",
                    "qty": 21211
                }
            ], [[12, {
                        "duration": 5000
                    }
                ]]]]]
```
![Clipboard01](https://user-images.githubusercontent.com/3178267/213913913-9583ec80-de14-4817-9e24-dcdb64b7df6b.jpg)

The Smithing action isn't interrupted at all and just keeps on making bars. Maybe I'm misinterpreting what the Wait action does?

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] I have searched for similar issues and nothing similar exists

**Comment by Alorel** [comment]
Oh, it was a hack for someone for something related to woodcutting, but I don't remember what - consider it deprecated and it'll be removed before v1.0.0. If you can read JS its definition is [here](https://github.com/Alorel/melvor-action-workflows/blob/ee1d7cce882dffd51cf065586eb53d43a6112a66/src/actions/core/delay-action.tsx#L20).

It basically blocks any follow-up actions or steps from executing for n milliseconds.

I really need to 1) Redesign the trigger picker 2) Add descriptions to each one 😅

**Comment by kellewic** [comment]
Ah, definitely misunderstood its purpose then.
