### ISSUE TITLE
And/Or check reset on trigger select

### ISSUE THREAD

**Issue by kellewic** [Alorel/melvor-action-workflows#95]
### Platform

Steam

### Category

A bugged trigger

### Bug description

And/Or Check getting reset back to And when selecting triggers within it.

### Steps to reproduce

1. Select And/Or trigger
2. Change Check to "Or"
3. Change next trigger to anything not selected
4. The Check in Step 2 will change back to "And"

This happens with subsequent trigger selections as well.

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] I have searched for similar issues and nothing similar exists

**Comment by Alorel** [comment]
Very likely related: #103

I should have time to start fixing stuff again tomorrow, been a busy week...

**Comment by Alorel** [comment]
Can't for the life of me find what's causing it to reset here... I think I'll just split it into two separate triggers to avoid needing that option in the first place
